import { themes } from "../constants/index.js";

export function T(theme) {
  let t = themes[theme];
  return {
    page: { minHeight: "100vh", background: t.bg, fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif", color: t.text, display: "flex", justifyContent: "center", padding: "20px 12px", transition: "background 0.3s, color 0.3s" },
    container: { width: "100%", maxWidth: "900px" },
    header: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "16px", flexWrap: "wrap", gap: "10px" },
    title: { fontSize: "20px", margin: 0, fontWeight: 700, color: t.textStrong },
    tabs: { display: "flex", gap: "4px" },
    tab: { padding: "6px 14px", borderRadius: "8px", border: `1px solid ${t.border}`, background: t.card, color: t.textMuted, fontSize: "13px", cursor: "pointer", fontWeight: 500 },
    tabActive: { padding: "6px 14px", borderRadius: "8px", border: `1px solid ${t.accent}`, background: t.accentBg, color: t.accent, fontSize: "13px", cursor: "pointer", fontWeight: 600 },
    adminBadge: { fontSize: "11px", background: t.goldBg, padding: "3px 8px", borderRadius: "20px", border: `1px solid ${t.goldBorder}`, color: t.gold },
    linkBtn: { fontSize: "11px", background: "none", border: "none", color: t.accent, cursor: "pointer", textDecoration: "underline", padding: 0 },
    themeBtn: { background: t.card, border: `1px solid ${t.border}`, borderRadius: "6px", padding: "4px 8px", cursor: "pointer", fontSize: "14px", lineHeight: 1 },
    weekPicker: { display: "flex", alignItems: "center", gap: "6px" },
    arrowBtn: { background: t.input, border: `1px solid ${t.inputBorder}`, color: t.textMuted, width: "32px", height: "32px", borderRadius: "6px", fontSize: "16px", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" },
    yearSelect: { fontSize: "14px", fontWeight: 600, color: t.textMuted, background: t.input, border: `1px solid ${t.inputBorder}`, borderRadius: "6px", padding: "5px 6px", cursor: "pointer", outline: "none" },
    weekSelect: { fontSize: "16px", fontWeight: 700, color: t.textStrong, background: t.input, border: `1px solid ${t.inputBorder}`, borderRadius: "6px", padding: "5px 8px", cursor: "pointer", outline: "none" },
    overlay: { position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "rgba(0,0,0,0.5)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100 },
    modal: { background: t.card, border: `1px solid ${t.border}`, borderRadius: "16px", padding: "24px 28px", minWidth: "280px", textAlign: "center" },
    pinInput: { width: "100%", padding: "10px 14px", fontSize: "18px", background: t.input, border: `1px solid ${t.inputBorder}`, borderRadius: "8px", color: t.textStrong, textAlign: "center", outline: "none", letterSpacing: "6px", boxSizing: "border-box" },
    textInput: { width: "100%", padding: "8px 12px", fontSize: "14px", background: t.input, border: `1px solid ${t.inputBorder}`, borderRadius: "8px", color: t.textStrong, outline: "none", boxSizing: "border-box" },
    selectInput: { width: "100%", padding: "8px 12px", fontSize: "14px", background: t.input, border: `1px solid ${t.inputBorder}`, borderRadius: "8px", color: t.textStrong, outline: "none", boxSizing: "border-box" },
    pinErr: { color: t.red, fontSize: "13px", margin: "8px 0 0 0" },
    modalBtnCancel: { flex: 1, padding: "9px", background: t.input, border: `1px solid ${t.inputBorder}`, borderRadius: "8px", color: t.textMuted, fontSize: "13px", cursor: "pointer" },
    modalBtnOk: { flex: 1, padding: "9px", background: t.accent, border: "none", borderRadius: "8px", color: "#fff", fontSize: "13px", fontWeight: 600, cursor: "pointer" },
    savedMsg: { textAlign: "center", color: t.green, fontSize: "13px", marginBottom: "8px", fontWeight: 600 },
    // cases
    goalsBar: { background: t.card, border: `1px solid ${t.border}`, borderRadius: "12px", padding: "14px 18px", marginBottom: "14px" },
    goalsTitle: { fontSize: "11px", textTransform: "uppercase", letterSpacing: "1px", color: t.textFaint, marginBottom: "10px", fontWeight: 600 },
    goalsRow: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(130px, 1fr))", gap: "10px" },
    goalCard: { background: t.cardAlt, borderRadius: "10px", padding: "12px", textAlign: "center", border: `1px solid ${t.borderLight}` },
    goalCatName: { fontSize: "11px", color: t.textMuted, textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: "4px" },
    goalNumbers: { display: "flex", alignItems: "baseline", justifyContent: "center", gap: "2px" },
    goalInput: { width: "50px", padding: "2px 6px", fontSize: "18px", fontWeight: 700, textAlign: "center", background: t.input, border: `1px solid ${t.accent}`, borderRadius: "6px", color: t.textStrong, outline: "none" },
    progressBg: { width: "100%", height: "4px", background: t.borderLight, borderRadius: "2px", marginTop: "6px", overflow: "hidden" },
    progressFill: { height: "100%", borderRadius: "2px", transition: "width 0.4s ease" },
    tableWrap: { overflowX: "auto", borderRadius: "12px", border: `1px solid ${t.border}`, background: t.card },
    table: { width: "100%", borderCollapse: "collapse", fontSize: "14px" },
    th: { padding: "10px 12px", textAlign: "center", fontWeight: 600, color: t.textMuted, fontSize: "11px", textTransform: "uppercase", letterSpacing: "0.5px", borderBottom: `1px solid ${t.border}`, background: t.cardAlt },
    dayCell: { padding: "10px 12px", fontWeight: 600, color: t.textMuted, borderBottom: `1px solid ${t.borderLight}` },
    cell: { padding: "6px 4px", textAlign: "center", borderBottom: `1px solid ${t.borderLight}` },
    cellInner: { display: "flex", alignItems: "center", justifyContent: "center", gap: "5px" },
    minusBtn: { width: "26px", height: "26px", borderRadius: "5px", border: `1px solid ${t.redBorder}`, background: t.redBg, color: t.red, fontSize: "15px", fontWeight: 700, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" },
    plusBtn: { width: "26px", height: "26px", borderRadius: "5px", border: `1px solid ${t.greenBorder}`, background: t.greenBg, color: t.green, fontSize: "15px", fontWeight: 700, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" },
    editInput: { width: "52px", padding: "4px 6px", fontSize: "15px", fontWeight: 700, textAlign: "center", background: t.input, border: `1px solid ${t.accent}`, borderRadius: "6px", color: t.textStrong, outline: "none" },
    totalCell: { padding: "10px 12px", textAlign: "center", fontWeight: 700, color: t.accent, fontSize: "15px", borderBottom: `1px solid ${t.borderLight}` },
    footLabel: { padding: "10px 12px", fontWeight: 700, color: t.textMuted, fontSize: "11px", textTransform: "uppercase", borderTop: `1px solid ${t.border}`, background: t.cardAlt },
    footCell: { padding: "10px 12px", textAlign: "center", fontWeight: 700, color: t.text, fontSize: "14px", borderTop: `1px solid ${t.border}`, background: t.cardAlt },
    grandCell: { padding: "10px 12px", textAlign: "center", fontWeight: 700, color: t.accent, fontSize: "15px", borderTop: `1px solid ${t.border}`, background: t.cardAlt },
    // schedule
    requestsBar: { background: t.goldBg, border: `1px solid ${t.goldBorder}`, borderRadius: "12px", padding: "12px 16px", marginBottom: "12px" },
    requestRow: { display: "flex", alignItems: "center", gap: "8px", padding: "6px 0", borderTop: `1px solid ${t.goldBorder}` },
    approveBtn: { padding: "4px 10px", borderRadius: "6px", border: "none", background: t.greenBg, color: t.green, fontSize: "12px", fontWeight: 600, cursor: "pointer" },
    denyBtn: { padding: "4px 10px", borderRadius: "6px", border: "none", background: t.dangerBg, color: t.red, fontSize: "12px", fontWeight: 600, cursor: "pointer" },
    requestBtn: { padding: "8px 16px", borderRadius: "8px", border: `1px solid ${t.inputBorder}`, background: t.input, color: t.accent, fontSize: "13px", fontWeight: 600, cursor: "pointer" },
    smallBtn: { padding: "6px 12px", borderRadius: "6px", border: `1px solid ${t.inputBorder}`, background: t.input, color: t.textMuted, fontSize: "12px", cursor: "pointer" },
    smallDangerBtn: { padding: "4px 8px", borderRadius: "4px", border: `1px solid ${t.dangerBorder}`, background: t.dangerBg, color: t.red, fontSize: "12px", cursor: "pointer", fontWeight: 700 },
    rolesBar: { display: "flex", gap: "10px", marginBottom: "14px", flexWrap: "wrap" },
    roleChip: { display: "flex", flexDirection: "column", gap: "2px", background: t.card, border: `1px solid ${t.border}`, borderRadius: "8px", padding: "6px 12px" },
    groupsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))", gap: "12px" },
    groupCard: { background: t.card, border: `1px solid ${t.border}`, borderRadius: "12px", padding: "14px", overflow: "hidden" },
    groupHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "4px", gap: "6px", flexWrap: "wrap" },
    groupName: { fontWeight: 700, color: t.textStrong, fontSize: "14px" },
    groupNameInput: { fontWeight: 700, color: t.textStrong, fontSize: "14px", background: "transparent", border: `1px solid ${t.inputBorder}`, borderRadius: "4px", padding: "2px 6px", outline: "none", width: "120px" },
    taskLabel: { fontSize: "12px", color: t.accent, fontWeight: 600, padding: "4px 8px", background: t.taskBg, borderRadius: "4px", display: "inline-block", cursor: "pointer" },
    schedTable: { width: "100%", borderCollapse: "collapse", fontSize: "12px" },
    schedTh: { padding: "6px 4px", textAlign: "center", fontWeight: 600, color: t.textMuted, fontSize: "11px", borderBottom: `1px solid ${t.borderLight}` },
    memberCell: { padding: "6px 8px", fontWeight: 600, color: t.text, fontSize: "12px", borderBottom: `1px solid ${t.borderLight}`, whiteSpace: "nowrap", position: "relative" },
    tinyDangerBtn: { position: "absolute", right: "2px", top: "50%", transform: "translateY(-50%)", background: "none", border: "none", color: t.red, fontSize: "14px", cursor: "pointer", padding: "0 2px", opacity: 0.5 },
    schedCell: { padding: "4px 2px", textAlign: "center", borderBottom: `1px solid ${t.borderLight}`, minWidth: "40px", borderRadius: "3px" },
    absSelect: { width: "100%", background: "transparent", border: "none", color: t.textStrong, fontSize: "13px", textAlign: "center", cursor: "pointer", outline: "none" },
    addMemberBtn: { marginTop: "6px", width: "100%", padding: "5px", borderRadius: "6px", border: `1px dashed ${t.inputBorder}`, background: "transparent", color: t.textFaint, fontSize: "11px", cursor: "pointer" },
    legend: { display: "flex", gap: "12px", marginTop: "14px", flexWrap: "wrap", justifyContent: "center" },
    legendItem: { display: "flex", alignItems: "center", gap: "4px" },
  };
}
